Add homepage, login and register components
tommyngo98/se-frontend pull request #3
Opened 2024-12-03 12:50 UTC by tommyngo98

2024-12-03 14:08 UTC, mirih2o requested changes
Route for HomeComponent: "./presentation/pages/home/home.component"

2024-12-03 14:08 UTC, mirih2o commented on src/app/app.routes.ts
> +import {HomeComponent} from "./presentation/pages/index/home.component";
"./presentation/pages/**home**/home.component"

2024-12-03 15:47 UTC, tommyngo98 commented on src/app/app.routes.ts
> +import {HomeComponent} from "./presentation/pages/index/home.component";
good catch

2024-12-04 17:16 UTC, mirih2o approved these changes

2024-12-04 17:34 UTC, merged